### ISSUE TITLE
运行一会出错了

### ISSUE THREAD

**Issue by jianxintongming** [An0nym6/LandlordsEndgame#4]
请输入地主牌：3 3 4 5 6 9 9 Q K 2 Y Z
请输入农民牌：5 7 9 10 10 J J Q K A 2

Traceback (most recent call last):
  File "D:\桌面\LandlordsEndgame-master\LandlordsEndgame-master\search.py", line 221, in <module>
    if searchTree(playerA, playerB, -1, -1, 0, root):
  File "D:\桌面\LandlordsEndgame-master\LandlordsEndgame-master\search.py", line 199, in searchTree
    if len(newPlayerB) == 0 or searchTree(newPlayerA, newPlayerB, move_['p'], move_['s'], level + 1, count) == 0:
  File "D:\桌面\LandlordsEndgame-master\LandlordsEndgame-master\search.py", line 199, in searchTree
    if len(newPlayerB) == 0 or searchTree(newPlayerA, newPlayerB, move_['p'], move_['s'], level + 1, count) == 0:
  File "D:\桌面\LandlordsEndgame-master\LandlordsEndgame-master\search.py", line 206, in searchTree
    tree = tree[:temp]

**Comment by An0nym6** [comment]
谢谢你关注这个仓库。这段代码只是简单地使用 DFS 去遍历 min-max 树，没有任何的启发和剪枝。下次提问请粘贴上完整的报错，而不只是错误的地点。照你的描述应该是内存错误，程序消耗的内存大于了你操作系统允许的内存而被强行 kill 掉。请参考另一篇 [Issue](https://github.com/An0nym6/LandlordsEndgame/issues/1)。再次感谢你的关注。
